### ISSUE TITLE
"You must be connected to Discord to create channels!"

### ISSUE THREAD

**Issue by michaeldawson** [thomasloupe/Slackord#44] opened 2023-01-12 20:49 UTC
Hi, thanks for your work on this bot! I'm unable to get it working. I've followed the instructions quite carefully (started from scratch and tried it twice so far), but run into the same issue:

```
➜  Slackord2_Mac_x64 ./Slackord
Slackord v2.4.3.4
Created by Thomas Loupe.
Github: https://github.com/thomasloupe
Twitter: https://twitter.com/acid_rain
Website: https://thomasloupe.com

Slackord will always be free!
If you'd like to buy me a beer anyway, I won't tell you not to!
You can donate at https://www.paypal.me/thomasloupe
You have the latest version, v2.4.3.4!
Found existing token file.
Please select an option:
1. Import Slack channels to Discord.
2. Import Slack messages.
1
You must be connected to Discord to create channels!
Please select an option:
1. Import Slack channels to Discord.
2. Import Slack messages.
```

I believe that `You must be connected to Discord to create channels!` is indicating a connection failure. I believe that the generated token is valid and is associated with valid permissions.

Any ideas how to proceed with debugging this?

Thanks!

**Comment by thomasloupe** [comment] 2023-01-12 21:29
Just as a quick way to test for this, if instead you place a JSON file that you wish to import into Discord in the Files folder, then select option 2 from the menu. Does it connect or does it fail?

**Comment by michaeldawson** [comment] 2023-01-16 18:36
Thanks for taking a look! I've pulled down the latest version, but unfortunately I run into JSON parse errors. Perhaps I'm not using it as you intended. I've run a slack bulk export, which created a number of folders with JSON files inside, plus a few top-level JSON files including "channels.json", etc. 

I initially tried to use this tool with the entire contents of this export in the Files directory. However, the output of the command indicated "Found 4 files in the Files folder", despite a large number of folders. I thought then that the script might not recursively grab files from folders - fair enough!

So, I ran a test with a single JSON file in the Files directory, from a per-channel export. Here's what happens if I run command "1" now:

```
➜  Slackord2_Mac_x64 ./Slackord
Slackord v2.4.3.5
Created by Thomas Loupe.
Github: https://github.com/thomasloupe
Twitter: https://twitter.com/acid_rain
Website: https://thomasloupe.com

Slackord will always be free!
If you'd like to buy me a beer anyway, I won't tell you not to!
You can donate at https://www.paypal.me/thomasloupe
You have the latest version, v2.4.3.5!
Found existing token file.
Please select an option:
1. Import Slack channels to Discord.
2. Import Slack messages.
1
Unhandled exception. %
```

Here's what happens if I run command "2":

```
./Slackord
Slackord v2.4.3.5
Created by Thomas Loupe.
Github: https://github.com/thomasloupe
Twitter: https://twitter.com/acid_rain
Website: https://thomasloupe.com

Slackord will always be free!
If you'd like to buy me a beer anyway, I won't tell you not to!
You can donate at https://www.paypal.me/thomasloupe
You have the latest version, v2.4.3.5!
Found existing token file.
Please select an option:
1. Import Slack channels to Discord.
2. Import Slack messages.
2
Reading JSON files directory...
Found 2 files in the Files folder.
Unexpected character encountered while parsing value: . Path '', line 1, position 3.
An error occured while parsing the JSON file. Please try again.
Reading JSON files directory...
Found 2 files in the Files folder.
Unexpected character encountered while parsing value: . Path '', line 1, position 3.
An error occured while parsing the JSON file. Please try again.
Reading JSON files directory...
Found 2 files in the Files folder.
Unexpected character encountered while parsing value: . Path '', line 1, position 3.
An error occured while parsing the JSON file. Please try again.
# (repeats indefinitely)
```

Here's a video demonstrating the issue with command 2: https://drive.google.com/file/d/1QdNyPGv8cxY7qfmFPk79Z7R3lRGdZI9X/view?usp=sharing

The file is of a valid JSON format.

**Comment by thomasloupe** [comment] 2023-01-16 18:49
Slackord doesn't look into subfolders. It's meant to be used on a per-channel basis and really kind of has no concept of what a "channel" really is in that sense. So just to ensure we're doing things as intended, your Files folder should contain only json files inside for a single channel's import.

Files:
--datetime.json
--datetime1.json
--datetime2.json

or

Files:
--channels.json

With that said, you should remove the channels.json file from your Files folder if not directly importing channels in that moment.

If you'd like, you can shoot me a message on Twitter with a link to the JSON that's failing (I don't need it all, just the first file), or upload the raw JSON here as a txt file and I can have a look at it and see where it's failing - otherwise, you can certainly download the source and run it in debug and place your JSON files in the Files folder in the debug run folder and send me the debug log.

**Comment by thomasloupe** [comment] 2023-02-08 11:10
Checking in on this issue to see if we have an update.

**Comment by thomasloupe** [comment] 2023-02-19 17:53
Closing issue. If you still need help with this, please open a new issue and reference this one.

**Closed as completed by thomasloupe** 2023-02-19 17:53 UTC
